### ISSUE TITLE
Error in test_pysoot.py: no textcrunchr_libs

### ISSUE THREAD

**Issue by Fr0stM0urne** [angr/pysoot#4]
I get this error when running ./test_pysoot.py

OSError: [Errno 2] No such file or directory: '/home/../pysoot-master/test/../..
/binaries-private/java/textcrunchr_libs

**Comment by ltfish** [comment]
It is a private binary file that we are not releasing.

**Comment by rhelmot** [comment]
The least we could do is have the test skipped if binaries-private isn’t cloned...

**Comment by antoniobianchi333** [comment]
Solved by: 30b3cda8adda99ef2d9fe45685168558a221c204
