### ISSUE TITLE
Pysoot Looping through shimple code?

### ISSUE THREAD

**Issue by anonymousgroundhog** [angr/pysoot#7]
I was going to ask if there is a way to loop through and extract each statement? 
For example suppose the following shimple code:
`//<pysoot.sootir.soot_class.SootClass object at 0x7fb8ffb91200>
 class HelloWorld extends java.lang.Object{

	//<pysoot.sootir.soot_method.SootMethod object at 0x7fb8ffbfd848>
	void <init>(){
		//<Block 0 [0], 3 statements>
		r0 <- @this[HelloWorld]
		r0.<init>() [specialinvoke java.lang.Object.<init>()]
		return null
	}
	
	//<pysoot.sootir.soot_method.SootMethod object at 0x7fb8ffbfdc48>
	public static void main(java.lang.String[]){
		//<Block 0 [0], 4 statements>
		r0 <- @parameter0[java.lang.String[]]
		$r1 = StaticFieldRef ('out', 'java.lang.System')
		$r1.println('"Hello, World"') [virtualinvoke java.io.PrintStream.println(java.lang.String)]
		return null
	}
	
}
`

I would let say want to modify $r1 to say instead of "Hello, World" "Hello, World2". How could I do this with the current architecture of pysoot?

**Comment by antoniobianchi333** [comment]
If I understand your question correctly:
you can iterate the list blocks of any method objects.
Within every block, you can iterate the list statements, to get all the instructions.
As an example, check the __str__ method in soot_method.py

pysoot returns Python objects, you are free to change them as you prefer (however Pysoot does not have any support to compiled them back to Java/Dex code).
